import { useAuth } from '../../context/AuthContext';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';

export default function Profile() {
  const { user, logout } = useAuth();

  return (
    <div className="max-w-2xl mx-auto space-y-8">
      <h1 className="text-3xl font-bold text-white">My Profile</h1>
      
      <Card className="p-8 border-slate-700 bg-slate-800/80">
        <div className="flex flex-col items-center sm:flex-row gap-6">
          <img 
            src={user?.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${user?.name}`} 
            alt="Avatar" 
            className="w-24 h-24 rounded-full bg-slate-700 p-1 border-2 border-indigo-500"
          />
          <div className="flex-1 space-y-1 text-center sm:text-left">
            <h2 className="text-2xl font-bold text-white">{user?.name}</h2>
            <p className="text-indigo-400 font-medium">@{user?.role}</p>
            <p className="text-slate-400">{user?.email}</p>
          </div>
        </div>

        <div className="mt-8 pt-8 border-t border-slate-700 space-y-4">
          <div>
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">User ID (50 Char UUID)</label>
            <div className="mt-2 p-3 bg-slate-950 rounded-lg border border-slate-700 font-mono text-xs text-green-400 break-all select-all">
              {user?._id}
            </div>
            <p className="text-[10px] text-slate-500 mt-1 text-right">Auto-generated by System</p>
          </div>

          <div>
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Joined At</label>
            <p className="text-slate-300 mt-1">{new Date(user?.createdAt).toLocaleString()}</p>
          </div>
        </div>

        <div className="mt-8 flex justify-end">
          <Button variant="danger" onClick={logout}>Sign Out</Button>
        </div>
      </Card>
    </div>
  );
}